config/routes.rb
Rails.application.routes.draw do
  resources :keywords, only: [:show]
  resources :memories do
    resources :comments
  end
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks",
                                    registrations: "registrations" }

  root 'thundrs#index'
end

app/models/memory.rb
class Memory < ActiveRecord::Base
  belongs_to :creator, class_name: "User"

  has_many :comments
  has_many :pending_replies,
           -> { where approved: false },
           class_name: "Comment"
  has_many :approved_comments,
           -> { where approved: true },
           class_name: "Comment"

  has_and_belongs_to_many :keyword_associations, class_name: "Keyword"
  has_many :related_memories,
           ->(m) { where.not(id: m.id) },
           through: :keyword_associations,
           source: :memories

  has_attached_file :image, styles: { large: "600x600>", medium: "450x450>" },
                            default_url: "/img-300-placeholder.gif"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true
  validates :keywords, presence: true
  validates :description, presence: true

  def related_memories_sorted
    related_memories.group("memories.id").count.sort_by { |_, v| v }.reverse.map { |k, _| Memory.find(k) }
  end

  def update_keyword_associations(new_keywords_string, old_keywords_string = "")
    new_keywords = to_keyword_array(new_keywords_string)
    old_keywords = to_keyword_array(old_keywords_string)

    add_keyword_associations(new_keywords - old_keywords)
    remove_keyword_associations(old_keywords - new_keywords)
  end

  def to_keyword_array(keyword_string)
    keyword_string.split(",").map(&:strip).map(&:downcase)
  end

  def remove_keyword_associations(removed_keyword_strings)
    removed_keyword_strings.each do |keyword|
      assoc = Keyword.find_by(word: keyword)
      keyword_associations.delete(assoc) if assoc
    end
  end

  def add_keyword_associations(added_keyword_strings)
    added_keyword_strings.each do |keyword|
      assoc = Keyword.find_or_create_by(word: keyword)
      keyword_associations << assoc unless keyword_associations.include? assoc
    end
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_memory, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized, only: [:update, :edit]

  def index
    @recent_memories = policy_scope(Memory).where.not(creator: current_user).order('created_at DESC').last(6)
  end

  def show
    # new comment for form helper
    @comment = Comment.new
    @related_memories = @memory.related_memories_sorted.first(5)
  end

  def edit
    authorize @memory
  end

  def new
    @memory = Memory.new
  end

  def create
    @memory = current_user.memories.build(memory_params)
    @memory.update_keyword_associations @memory.keywords

    if @memory.save
      redirect_to @memory, notice: 'Memory was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @memory

    @memory.update_keyword_associations memory_params[:keywords], @memory.keywords

    if @memory.update(memory_params)
      redirect_to @memory, notice: 'Memory was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @memory
    @memory.destroy
    redirect_to memories_path, notice: 'Memory was successfully declined.'
  end

  private

  def set_memory
    @memory = Memory.find(params[:id])
  end

  def memory_params
    params.require(:memory).permit(:name, :keywords, :description, :creator_id, :image)
  end
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/views/memories/_form.html.erb
<%= form_for(@memory) do |f| %>
  <% if @memory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memory.errors.count, "error") %> prohibited this memory from being saved:</h2>

      <ul>
      <% @memory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field">
      <%= f.label :name, class: "form-label"%><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <span data-tooltip aria-haspopup="true" class="has-tip" title="Comma seperate keywords">
      <%= f.label :keywords, class: "form-label" %><br>
      <%= f.text_field :keywords %>
    </span>
    </div>

    <div class="field">
      <%= f.label :description, class: "form-label" %><br>
      <%= f.text_area :description %>
    </div>
  </div>
   <%= f.label :image, class: "form-label" %><br>
  <div class="row">

    <div class="medium-4 columns">
      <div class="field">
       <%= f.file_field :image, class: "button round right" %>
      </div>
    </div>

    <div class="actions large-4 columns">
      <%= f.submit class: "button round left" %>
    </div>
  </div>

<% end %>

app/views/memories/edit.html.erb
<h1>Editing Memory</h1>

<%= render 'form' %>

app/views/memories/index.html.erb
<div class="row" id="recent_memories">
  <div class="small-12 columns panel radius">
    <h2>Recently shared memories<h2>
    <div class="row">
      <% @recent_memories.each do |memory| %>
        <div class="left large-2 medium-4 small-6 columns memory" id="memory-<%= memory.id %>">
          <%= link_to image_tag(memory.image.url(:medium), class: "memory-image"), memory %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="row" id="related_memories">
  <div class="small-12 columns panel radius">
    <h2>Memories similar to your own<h2>
    <div class="row">
      <% current_user.related_memories.first(6).each do |memory| %>
        <div class="left large-2 medium-4 small-6 columns memory" id="memory-<%= memory.id %>">
          <%= link_to image_tag(memory.image.url(:medium), class: "memory-image"), memory %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="row" id="your_memories">
  <div class="small-12 columns panel">
    <div class="row">
      <div class="medium-6 small-12 columns">
        <% if current_user.memories.count < 1 %>
          <h2> Add Your First Memory</h2>
          <%= link_to 'New Memory', new_memory_path, class: "radius button round" %>
        <% else %>
        <h2>Your Recent Memories</h2>
        <% end %>
      </div>

    </div>
    <div class="row">
      <% @current_user.memories.each do |memory| %>
        <div class="left large-4 medium-6 small-12 columns memory" id="memory-<%= memory.id %>">
          <%= link_to image_tag(memory.image.url(:medium), class: "memory-image"), memory %>
          <div>
            <h5><%= memory.name %></h5>
            <h6 class="subheader">
              <%= memory.keyword_associations.map{ |kw| link_to kw.word, kw }.join(", ").html_safe %>
            </h6>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="row" id="pending_comments">
  <% unless current_user.pending_replies.empty? %>
    <div class="small-12 columns panel">
      <div class="row">
        <h2>Replies to your memory</h2>
      </div>
      <div class="row">
        <% current_user.memories_with_pending_replies.each do |memory| %>
          <div class="medium-2 columns">
            <%= link_to image_tag(memory.image.url, class: "memory-image"), memory %>
          </div>

          <div class="medium-10 columns">

            <% memory.pending_replies.each do |reply| %>
              <div class="comment panel callout radius">
                <div class="row">
                  <div class="small-6 columns">
                  <b><%= reply.author.username %></b> says:
                  </div>
                  <div class="small-6 columns">
                    <%= reply.created_at.strftime("%m/%-d/%Y") %>
                  </div>
                </div>

                <div class="row">
                  <div class="small-12 columns">
                    <%= reply.body %>
                  </div>
                </div>

                <div class="row">
                  <div class="small-6 columns">
                    <%= form_for([reply.memory, reply]) do |f| %>
                      <%= f.submit 'Accept', class: "button success round" %>
                      <%= f.hidden_field :approved, value: true %>
                    <% end %>
                  </div>
                  <div class="small-6 columns">
                    <%= form_for([reply.memory, reply]) do |f| %>
                      <%= f.hidden_field :approved, value: true %>
                      <%= f.submit 'Delete', method: :delete, data: { confirm: 'Are you sure?' }, class: "button alert round" %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/memories/new.html.erb
<div class="row">
  <h1>New Memory</h1>
</div>
<%= render 'form' %>

app/views/memories/show.html.erb
<div class="memory" id="memory-<%= @memory.id %>">
  <div class="panel callout radius">

    <p>
      <strong>Name:</strong>
      <em><%= @memory.name %></em>
    </p>
    <%= image_tag @memory.image.url(:large), class: "memory-image" %>
    <p>
      <strong>Keywords:</strong>
      <%= @memory.keyword_associations.map{ |kw| link_to kw.word, kw }.join(", ").html_safe %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @memory.description %>
    </p>
    <p>
      <strong>Author:</strong>
      <%= @memory.creator.username %>
    </p>
    <ul class="button-group">
      <% if policy(@memory).edit? %>
        <%= link_to 'Edit', edit_memory_path(@memory), class: "button round" %>
      <% end %>
      <% if current_user.role == 'admin' %>
        <%= link_to 'Delete Memory', @memory, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </ul>
 </div>

  <div class="row">
    <div class="large-8 columns">
    <% if @memory.approved_comments.count > 0 %>
      <h3> Comments: </h3>
      <% @memory.approved_comments.each do |reply| %>
        <div class="panel radius">
          <%= reply.body %> <br />
          <% if current_user.role == 'admin' %>
            <%= link_to 'Delete Comment', @reply, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        <% end %>
    <% end %>
      <%= render 'comments/form' %>
      </div>
      <div class="large-4 columns">
        <% @related_memories.each do |related_memory| %>
          <div class="row">
            <div class="small-12 columns memory">
              <%= link_to(image_tag(related_memory.image.url(:medium)), related_memory) %><br />
            </div>
          </div>
       <% end %>
      </div>
    </div>
  </div>
</div>